### ISSUE TITLE
Transform API

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#10]
We've talked a bit about how to handle provenance and track table mutations.

## Option 1: just save everything

One option is to save a copy of the data after every transformation and allow a client to keep references to the transformation versions it cares about.  For example, the client would be responsible for coordinating order-of-operations if it changed normalization.

## Option 2 (proposed): transform catalog.

**Assumption**: transformations are cheap and easy to recompute.

Introduce a new transformation table to the data model with the following schema:

| id | csv_data_id | transformation_name | priority | parameters |
|----|-------------------|-------------------------------|------------|-----------------|
| `uuid primary key` | `uuid foriegn key to CSV table` | `a name, such as "median normalization"` | `a number in [1, +inf)` | `freeform dictionary` |

Then the client could create and modify the collection of transformations applied to a particular source data table.  On each mutation to the transformation table, the backend could apply all transformations for a data table ordered by priority. 

I'm imagining that all data sets would have two copies of itself on the server: an immutable copy of the original data and a mutable copy with whatever the current transformations are applied.

This is auditable and persists through browser sessions, would allow transformations to have a simple api, and reduce complexity in the frontend. 

Happy to contribute here.  cc @jbeezley

**Comment by jbeezley** [comment]
I'm on board with something like Option 2.  A few things prevent me from wanting to implement it just yet.
1. Individually transforms should be cheap, but because we have to pass them off to R there is a significant overhead per transform (probably >100ms minimum).  If we have to run a full chain of transforms serially to get reactive updates coming from the client, we will have performance issues.  To address this we could implement memoization/caching or aggregation of transforms.
2. Some transforms will inevitably require more than one csv file, e.g. cross correlation
3. The output from some transforms won't be tables (e.g. a number/vector) or will be a table that does not represent metabolites as columns and samples as rows (e.g. a covariance matrix).
4. Brushing the details of a transform into free form json makes me uncomfortable because it very much resembles our "fact" table from DIVA.

Ultimately what I would like before adding to much engineering effort is a preliminary catalog of transformations for an alpha version of the application.  I think having this would also help motivate the design of the UI for you and Jared.

**Comment by jbeezley** [comment]
I'm working on a proof of concept of this right now.  I'm thinking the key to making it work will to be properly scope out what a "transform" means:
1. It takes a single table as output and returns a single table as output.
2. All tables have metabolites as column headers and rows are samples (possibly with unique entity id's).
3. Transforms can take arbitrary keyword arguments, but each should provide a schema for validation.
4. Transforms cannot take foreign key as an argument to get around (1).

Anything that doesn't satisfy these conditions should be a different kind of entity.  I'm targeting specifically things like:
1. Set a value (`table[row, column] = value`)
2. Remove a specific column or row.
3. Normalize a column.
4. Fill missing values.

One issue that I'm currently grappling with is what this means in terms of storing the rows and/or columns that exist for a given csv file.  Clearly transforms can change this.  Do we store the rows/columns that exist after applying the transform chain, or do we abandon these tables and do it in the serialization?  The answer will depend on if there will ever be a need to query (or join) csv files.  At the moment, I don't think it will be necessary, but I also don't know all the use cases we are targeting.

**Comment by jbeezley** [comment]
An alpha implementation was added in #15
