### ISSUE TITLE
Web client performance issues

### ISSUE THREAD

**Issue by jbeezley** [girder/metabulo#148]
When loading large tables, the web client can lag considerably.  For example, [this csv file](https://gist.github.com/jbeezley/3c8c4afa075e82d3608d8c3394eb6806) contains over 1000 columns.  On my desktop, just selecting a column (no server side requests) takes between 1-2 seconds.  On a slow laptop, I can get the UI to freeze up for more than 10 seconds by clicking around.

We should look into only rendering the rows/columns in view.

**Comment by subdavis** [comment]
First thing I want to try is `table-layout:fixed;`

**Comment by subdavis** [comment]
After that, https://github.com/vuejs/vue/issues/2000 is a good place to look.   Custom directives might speed things up.

**Comment by jeffbaumes** [comment]
+1 these look like reasonable approaches. Let us know how they go.

**Comment by matthewma7** [comment]
my 2 cents here
Maybe the time is taken by turning all the data into observables instead of rendering? which is an issue@jeffbaumes has observed before with vuejs. 
I am curious if the data attached to the `data` of a vue component? maybe try not to define it on the data? and import it directly in the scope and expose them together as a whole object via a computed or a method?

**Comment by subdavis** [comment]
After some profiling and playing around, I think I've identified the problem and a path forward.

I've run into `data -> observables` being expensive over in TDM, and that isn't the issue here.  Table data doesn't change (much) and takes less than a second to process.

This is definitely a rendering issue.  The cost of re-rendering the table when selection changes and diffing it with the DOM is where the slowness is coming from.

I experimented with custom directives and rendering the table with `createElement` and `appendChild`, and the upfront cost doesn't drop much. It still takes a second or two to render the initial table.  This isn't avoidable, and you can see the same performance hit if you profile the [github page with the csv jon linked](https://gist.github.com/jbeezley/3c8c4afa075e82d3608d8c3394eb6806).

However, I expect huge cost savings if I can come up with a sane way to avoid re-rendering the table on selection and class changes.  All I really need to do is iterate over the table rows and colgroups and edit the classes directly on the DOM.  The key will be to avoid changing the widths/heights of anything on selection change, so the pixel shift problem needs a solution to avoid layout thrashing (I think).   

Confidence level that we can get good performance out of the current app without any major UI design change: 70%.

**Comment by subdavis** [comment]
# Options for resolving performance issues

The following are options for how to resolve this issue.  Times are listed as how long it takes to complete a selection change for the large CSV above.  ranked in order of my own preference.

1. Do nothing (baseline).  Updates take 2.5-2.8 seconds.  Ranked 4.
2. Adopt #154.  Updates take 100ish ms.  Can't draw selected columns over special rows (see issue).  I prefer this option short-term, Ranked 1.
3. Adopt #156.  Updates take 800ish ms.  Looks and works identically to the current interface.  Ranked 2.
4. Adopt #156 with reactivity removed.  650-700ms.  Minimal performance gains for large code quality hit.    Ranked 3.

# More options

If we were to abandon some of the current design, [canvas-datagrid](https://github.com/TonyGermaneri/canvas-datagrid) looks to be a really high-quality canvas option.  I think I could reproduce the basic formatting there.

**Comment by waxlamp** [comment]
Are these options orthogonal to the notion of allowing the user to batch update several changes made only in the front end (i.e. without round-tripping each update to the server immediately)?

**Comment by matthewma7** [comment]
Note to self. This series of issue and PR can be used for reference for Vue rendering optimization in future.

**Comment by subdavis** [comment]
@waxlamp yes, I'm not taking RTTs into account here.  I think it would be good to discuss the merits and costs of batching elsewhere.  logged #157
