### ISSUE TITLE
Dataset Validation Schema

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#84]
To produce the views in #83, some kind of schema for data validation will be necessary.

It would be ideal to shape it something like this:

```javascript
      validation: [
        { severity: 'error', type: 'primary-key', title: 'Primary key missing' },
        { severity: 'error', type: 'group-tag', title: 'Group tag missing' },
        {
          severity: 'error', type: 'missing-data', title: 'Missing data', data: [3, 4, 15, 18, 22, 23, 24, 25, 26, 27, 28, 29],
        },
        {
          severity: 'warning', type: 'low-variance', title: 'Low variance', data: [5, 6, 7, 9, 12, 14],
        },
      ],
```

Where `severity`, `type`, and `title` are required and `data` could either be a list of the column indexes where that applies or a list of objects with more data about each instance, such as percent missing or r^2, respectively.

```javascript
data: [
  { index: 34, missing: .34 },
]
```

We could also encode a map of `type -> (title, description, severity)` in the client code and remove those as requirements from the schema, but that would require client changes if the enum of possible validation errors changed.

cc @jbeezley is this along the lines of what you were thinking?

Side note: right now  there's a table validation error `Error applying transforms`.  I don't think this should be a validation error.  If transforms fail and the server can't determine a validation reason, that should probably be some kind of 400 or even 500 error.

**Comment by jbeezley** [comment]
I can work with that schema.

RE: missing data.  It will be a warning because the imputation step will automatically fill in all missing values.  Also, the R script keeps track of missing data per group.  So there could be multiple missing data warnings per column that each apply to a subset of rows.  

> We could also encode a map of type -> (title, description, severity) in the client code and remove those as requirements from the schema, but that would require client changes if the enum of possible validation errors changed.

I'm okay with keeping it server-side, but I doubt we will be able to decouple the definition from the client side implementation.  The client will need to understand the details of the error to suggest solutions or provide more context.

> Side note: right now there's a table validation error Error applying transforms. I don't think this should be a validation error. If transforms fail and the server can't determine a validation reason, that should probably be some kind of 400 or even 500 error.

We could return an HTTP error code, but I'm imagining a hypothetical scenario where two parameters need to change at once in different steps.  (Setting each individually would cause an error in the pipeline.)  We would need to provide a single endpoint to set both parameters at once.

I do plan to provide the error coming from R to provide more information (mostly for our debugging purposes).  Eventually, we may have a need to define an "errror api" for the R service to provide context for known errors.  That could replace most instances of this generic failure provided we can predict all the things that could go wrong with the algorithm.

**Comment by jbeezley** [comment]
The original script does the following:
1.  Removes columns with > 25% missing data in **all** groups
2.  For single groups missing >= 70%, sets missing values to 0
3.  For columns with all groups missing <= 40% data, run a KNN to fill values
4.  Use a KNN to fill in the remaining missing values

The imputation step in metabulo only does 2-4.  I'm planning on a different endpoint to do 1 as a "bulk" operation.

The point I'm making is that the imputation algorithm as it exists will fill in **all** missing values regardless.  Clearly though, it won't do a very good job if too many are missing, but it can proceed.  That's why I think it's a warning, not an error.

**Comment by subdavis** [comment]
@jbeezley got it.  Those should be warnings then.  And some of them aren't actionable: If the script removes columns, there's no action the user can take except adjusting the parameters of the script and rerunning it.

**Comment by subdavis** [comment]
FYI: don't go out of your way to make the results conform to this schema if something else makes more sense.   The only nice-to-have for me would be separating all the different types of errors into logical groups.
